name: Build custom version of RustDesk

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        description: "upload artifacts"
        default: true
        required: false
        type: boolean
      upload-tag:
        description: "tag to upload (e.g., asci, asci-in-debug)"
        required: true
      customization:
        description: "customization (JSON)"
        required: true
      build_windows:
        description: 'Build for Windows'
        type: boolean
        default: true
      build_macos:
        description: 'Build for macOS'
        type: boolean
        default: true
      build_linux:
        description: 'Build for Linux'
        type: boolean
        default: true
      build_android:
        description: 'Build for Android'
        type: boolean
        default: true

# placeholder / definition of inputs, for use in master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo Hello, world!